=== Geiko/cSharp/DZ 8 XML/ReadXML/ReadXML/files/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://itstep.org/students"
        xmlns:tns="http://itstep.org/students">
	<element name="students">
		<complexType>
			<sequence>
				<element name="student" type="tns:Student"
				         minOccurs="1" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>

	<complexType name="Student">
		<sequence>
			<element name="name" type="string"/>
			<element name="phone" type="decimal"/>
			<element name="address" type="tns:Address"/>
		</sequence>
		<attribute name="login" type="tns:Login" use="required"/>
		<attribute name="faculty" type="string" use="required"/>
	</complexType>

	<simpleType name="Login">
		<restriction base="ID">
			<pattern value=".*"/>
		</restriction>
	</simpleType>

	<complexType name="Address">
		<sequence>
			<element name="country" type="string"/>
			<element name="city" type="string"/>
			<element name="street" type="string"/>
		</sequence>
	</complexType>

</schema>

=== Geiko/cSharp/DZ 8 XML/ReadXML/ReadXML/bin/Debug/files/newStudents.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:students xsi:schemaLocation="http://itstep.org/students students.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://itstep.org/students">
  <student login="log" faculty="fac">
    <name>Natasha</name>
    <phone>324587</phone>
    <address>
      <country>UA</country>
      <city>DP</city>
      <street>KM</street>
    </address>
  </student>
  <student login="log2" faculty="fac2">
    <name>Lola</name>
    <phone>98765</phone>
    <address>
      <country>USA</country>
      <city>SD</city>
      <street>SP</street>
    </address>
  </student>
</tns:students>

=== Geiko/cSharp/DZ 8 XML/ReadXML/ReadXML/files/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:students xmlns:tns="http://itstep.org/students"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://itstep.org/students students.xsd"
		>
	<student login="vas" faculty="programming">
		<name>Vasya Pupkin</name>
		<phone>3323233232</phone>
		<address>
			<country>UA</country>
			<city>DP</city>
			<street>KM</street>
		</address>
	</student>
	<student login="pet" faculty="programming">
		<name>Petya Grishin</name>
		<phone>4454577845</phone>
		<address>
			<country>UA</country>
			<city>DP</city>
			<street>KM</street>
		</address>
	</student>
</tns:students>
